### ISSUE TITLE
DB error/missing

### ISSUE THREAD

**Issue by esdeath11** [Oktavxxa/Project_PBO2#1]
![image](https://user-images.githubusercontent.com/48850021/122666026-28579600-d1d5-11eb-86d0-7956e6273690.png)

**Comment by Oktavxxa** [comment]
maaf mas baru bales, dbnya itu mas pbo_db.sql

Pada tanggal Sel, 22 Jun 2021 pukul 20.39 yafie M. Sa. A <
***@***.***> menulis:

**Comment by esdeath11** [comment]
Btw file main mu gk ada extension  .py
